name: chatapp
description: End-to-end encrypted chat app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  web_socket_channel: ^3.0.3
  cryptography: ^2.1.0
  flutter_secure_storage: ^10.0.0
  flutter_local_notifications: ^19.0.0
  uuid: ^4.3.3
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
